#!/bin/sh
/sbin/pidof /home/tbumgarner/webapps/photo20/bin/node > /dev/null 2>&1 && exit 0
mkdir -p /home/tbumgarner/webapps/photo20/run
nohup /home/tbumgarner/webapps/photo20/bin/node /home/tbumgarner/webapps/photo20/ui/server.js > /dev/null 2>&1 &
/sbin/pidof /home/tbumgarner/webapps/photo20/bin/node > /home/tbumgarner/webapps/photo20/run/node.pid
