# Generated by Django 2.1.1 on 2018-09-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='website',
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='Foo', max_length=200),
            preserve_default=False,
        ),
    ]
