# Generated by Django 2.1.1 on 2018-09-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('summary', models.CharField(max_length=500, unique=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('date', models.DateField(null=True)),
            ],
        ),
    ]
