# Generated by Django 2.1.1 on 2018-10-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='src',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
