# Generated by Django 2.1.1 on 2018-09-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20180903_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='date',
            new_name='date_taken',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='meta',
            new_name='exif_data',
        ),
        migrations.AddField(
            model_name='photo',
            name='year',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
