# Generated by Django 2.1.1 on 2018-09-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_auto_20180903_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=2500)),
            ],
        ),
    ]
