# Generated by Django 2.1.1 on 2018-09-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20180902_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='file_name',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='src',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
