# Generated by Django 2.1.1 on 2018-09-05 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
