# Generated by Django 2.1.1 on 2018-09-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_auto_20180905_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='color_sample_1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='color_sample_2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='exif_data',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='width',
            field=models.IntegerField(null=True),
        ),
    ]
