# Generated by Django 2.1.1 on 2018-09-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_photo_src_thumbnail_small'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='src_thumbnail_medium',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
