# Generated by Django 2.1.1 on 2018-09-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0011_photo_src_thumbnail_medium'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='aperature',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='camera_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='iso',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='lens',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='make',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='model',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='shooting_mode',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='shutter_speed',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
