# Generated by Django 2.1.1 on 2018-09-09 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0012_auto_20180909_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='aperature',
            new_name='aperture',
        ),
    ]
