# Generated by Django 2.1.1 on 2018-09-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0013_auto_20180909_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='focal_length',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
