# Generated by Django 2.1.1 on 2018-09-30 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0016_auto_20180930_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='color_sample_1',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='color_sample_2',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='year',
        ),
    ]
