# Generated by Django 2.1.1 on 2018-09-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0017_auto_20180930_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='photo',
            name='categories',
        ),
        migrations.AddField(
            model_name='photo',
            name='category',
            field=models.ManyToManyField(null=True, to='photos.Category'),
        ),
    ]
