# Generated by Django 2.1.1 on 2018-09-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0018_auto_20180930_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.ManyToManyField(to='photos.Category'),
        ),
    ]
