# Generated by Django 2.1.1 on 2018-10-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0020_auto_20180930_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_home_background',
            field=models.BooleanField(default=False),
        ),
    ]
