# Generated by Django 2.1.1 on 2018-10-14 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0021_photo_is_home_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='title',
        ),
    ]
